
## DB ###
spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none #create, create-drop, none, update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy # set DB column name by snake case
    show-sql: true
    generate-ddl: true
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER # Swagger-ui

  ### DB initialize auto insert ###
  sql:
    init:
      mode: always
      encoding: utf-8
      # data-locations: "classpath: data.sql" #use different file for initializing data
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
jwt:
  secret: ${JWT_TOKEN_SECRET_KEY}
sns:
  kakao:
    key: ${KAKAO_API_KEY}
    url: ${KAKAO_REDIRECT_URL}
sms:
  key: ${SMS_API_KEY}
  secret: ${SMS_API_SECRET_KEY}
  phoneNumber: ${PHONE_NUMBER}
mail:
  id: ${NAVER_ID}
  password: ${NAVER_PASSWORD}